### ISSUE TITLE
Feedback Opdracht 3

### ISSUE THREAD

**Issue by RobertDux** [marithoek/DUPLO3#1]
## Algemeen

- Superleuk ontwerp!
- Goede structuur van code en bestandsnamen.
- Ik kan een wachtwoord van 20000 karakters genereren, misschien wat afvangen?

## HTML

- Probeer in je klassen niet dezelfde namen te gebruiken met een nummer erachter.
- De `alt` teksten voor een afbeelding mogen een zin zijn.
- Alternatief voor de klassen `passwordstrengthdiv`, `passwordStrength` en `passwordPercentage`:

```html
<div class="password-strength">
  <span class="password-strength__text"></span>
  <span class="password-strength__percentage"></span>
</div>
```

## CSS

- Veel van je `glitter`, `mijnAfbeelding` en `mijnTekst` stijlen hebben overlap. Deze overlap kan je in een aparte klasse opnemen:

```css
.glitter {
  position: absolute; /* common styles */
}

.glitter--uppercase {
  left: 5%; /* unique styles for uppercase */
}

.glitter--letters {
  top: 4%;
}
```

## JavaScript

- Vermijd `onclick` in je HTML, maar gebruik `addEventListener`.
- Gebruik geen `var`, maar `const` of `let`.
- Elke variabele krijgt zijn eigen regel.
- `GLOBALE_VARIABELEN` zijn op deze manier geschreven.
- Gebruik geen Engels en Nederlands door elkaar.
